bottom = @(x,y) x.^2 + y.^2;
top    = @(x,y) 16 + 0*x;

surfaceToSTL( ...
    'paraboloid.stl', ...
    bottom, ...
    top, ...
    4, ...       % radius
    80, ...      % radial resolution
    160);        % angular resolution